name: laravel

on:
  push:
    branches: 10.x


jobs:
  laravel-deployment:
    runs-on: ubuntu-latest

    steps:
     - name: Deploy laravel Application
       uses: appleboy/ssh-action@v1.0.0
       with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: ${{ secrets.PORT }}
        script: |
          cd /var/www/html/laravel
          git pull
          php artisan cache:clear
          php artisan config:clear
          php artisan view:clear
          php artisan route:clear

