name: laravel

on:
  push:
    branches: 10.x


jobs:
  laravel-deployment:

    runs-on: ubuntu-latest

    steps:
     - name: Deploy cleverfuze Application
       uses: appleboy/ssh-action@v0.1.2
       with:
        host: ${{ secrets.SSH_HOST_STAGING }}
        username: ${{ secrets.SSH_USERNAME }}
        password: ${{ secrets.SSH_PASSWORD }}
        script: |
          cd /var/www/laravel
          git pull
          php artisan cache:clear
          php artisan config:clear
          php artisan view:clear
          php artisan route:clear

