name: cleverfuse

on: 
  push:
    branches: [ "staging" ]


jobs:
  cleverfuse-deployment:

    runs-on: ubuntu-latest

    steps:
     - name: Deploy cleverfuze Application
       uses: appleboy/ssh-action@master
       with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd /var/www/cleverfuse
          git pull
          php artisan cache:clear
          php artisan config:clear
          php artisan view:clear
          php artisan route:clear
