name: Create Text File on Server

on:
  push:
    branches:
      - 10.x

jobs:
  create-file-on-server:
    runs-on: ubuntu-latest

    steps:

      - name: Create text file on server
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.PORT }}

          script: |
             touch /home/ubuntu/laravel/aws.txt
